name:                borl
version:             0.1.0.0
github:              "github.com/schnecki"
license:             AllRightsReserved
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schneckenreither@uibk.ac.at"
copyright:           "2018 Manuel Schneckenreither"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Blackwell optimal reinforcement learning
category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/borl#readme>

flags:
  fast:
    description: Disables optimizations
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5
  - containers
  - random
  - lens
  - pretty
  - text
  - singletons
  - hmatrix
  - vector
  - grenade
  - parallel
  - deepseq
  - time
  - mtl
  - tensorflow
  - tensorflow-core-ops
  # - tensorflow-logging
  - tensorflow-mnist-input-data
  - tensorflow-mnist
  # - tensorflow-opgen
  - tensorflow-ops
  # - tensorflow-proto
  # - tensorflow-records-conduit
  # - tensorflow-records
  - HUnit

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -fwarn-tabs
  when:
    - condition: flag(fast)
      then:
        ghc-options: -O0
      else:
        ghc-options: -O2

executables:
  gridworld:
    main:                Gridworld.hs
    other-modules:       Helper
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borl

  gridworld-mini:
    main:                GridworldMini.hs
    other-modules:       Helper
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borl

  multichain:
    main:                Multichain.hs
    other-modules:       Helper
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borl

  three-states:
    main:                ThreeStates.hs
    other-modules:       Helper
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borl

  tensorflow-test:
    main:                Tensorflow.hs
    source-dirs:         examples
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


tests:
  borl-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - borl
      - QuickCheck
      - hspec

