flags: {}
packages:
- .
- experimenter
- grenade
- gym-haskell
- gym-haskell/haskell-cpython
- high-level-tensorflow
extra-deps:
- hmatrix-glpk-0.19.0.0@sha256:cf46c54bc3878bd207674ad88c3389083809f4df862df68ee64c6708dc517a52,1683
- git: https://github.com/tensorflow/haskell
  commit: 8cde4d6a277f188ca495d29096a62b36e8534a3f
  subdirs:
  - tensorflow
  - tensorflow-core-ops
  # - tensorflow-logging
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  - tensorflow-opgen
  - tensorflow-ops
  - tensorflow-proto
  # - tensorflow-records
  # - tensorflow-records-conduit
  # - tensorflow-test
allow-newer: false
resolver: lts-14.25
