flags: {}
packages:
- .
- grenade
- tensorflow-haskell/tensorflow
- tensorflow-haskell/tensorflow-core-ops
- tensorflow-haskell/tensorflow-logging
- tensorflow-haskell/tensorflow-mnist
- tensorflow-haskell/tensorflow-mnist-input-data
- tensorflow-haskell/tensorflow-opgen
- tensorflow-haskell/tensorflow-ops
- tensorflow-haskell/tensorflow-proto
- tensorflow-haskell/tensorflow-records
- tensorflow-haskell/tensorflow-records-conduit
- tensorflow-haskell/tensorflow-test
extra-deps:
- snappy-framing-0.1.2
- intero-0.1.30
# allow-newer: true
resolver: lts-12.26
