flags: {}
packages:
- .
- ../experimenter
- ../easy-logger
- ../hasktorch/hasktorch
- ../hasktorch/libtorch-ffi
- ../hasktorch/libtorch-ffi-helper
- ../welford-online-mean-variance

extra-include-dirs:
- ../hasktorch/deps/libtorch/include/torch/csrc/api/include
- ../hasktorch/deps/libtorch/include

extra-lib-dirs:
- ../hasktorch/deps/libtorch/lib
- ../hasktorch/deps/mklml/lib
- ../hasktorch/deps/libtokenizers/lib


extra-deps:
- bytestring-0.10.12.1@sha256:82dba4c2de4fdd8b419ed28aec2c14cfe4a3f43d1d6e2263ab26962e7398048e,6254
- git: https://github.com/fpco/inline-c.git
  commit: 2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0
  subdirs:
  - inline-c-cpp
  - inline-c

allow-newer: true # false
resolver: lts-19.25
