flags: {}
packages:
- .
- experimenter
- grenade
- gym-haskell
- tensorflow-haskell/tensorflow
- tensorflow-haskell/tensorflow-core-ops
- tensorflow-haskell/tensorflow-logging
- tensorflow-haskell/tensorflow-mnist
- tensorflow-haskell/tensorflow-mnist-input-data
- tensorflow-haskell/tensorflow-opgen
- tensorflow-haskell/tensorflow-ops
- tensorflow-haskell/tensorflow-proto
- tensorflow-haskell/tensorflow-records
- tensorflow-haskell/tensorflow-records-conduit
- tensorflow-haskell/tensorflow-test
extra-deps:
- cpython-3.4.0@sha256:7fdd6ecacaab4fa60d975e5a8f91fee6b07a80cf4936d9a407b3f64b9a1732ad,1956
- hmatrix-glpk-0.19.0.0@sha256:cf46c54bc3878bd207674ad88c3389083809f4df862df68ee64c6708dc517a52,1683
- snappy-framing-0.1.2@sha256:68c8f44e7b1e04d0342b83bae62f390350875bc4fcf4c203c0ad012323508f64,1196
- snappy-0.2.0.2@sha256:2931b03c5fdab2dac8d7eadb3be2f4ef8906666e43f1f1db65a06efd57ea701b,1591
allow-newer: false
resolver: lts-14.8
