flags: {}
packages:
- .
- ../
- ../../easy-logger
- ../../experimenter
- ../../haskell-cpython
- ../../gym-haskell
- ../../hasktorch/hasktorch
- ../../hasktorch/libtorch-ffi
- ../../hasktorch/libtorch-ffi-helper
- ../../welford-online-mean-variance

extra-include-dirs:
- ../../hasktorch/deps/libtorch/include/torch/csrc/api/include
- ../../hasktorch/deps/libtorch/include

extra-lib-dirs:
- ../../hasktorch/deps/libtorch/lib
- ../../hasktorch/deps/mklml/lib
- ../../hasktorch/deps/libtokenizers/lib

extra-deps:
- hmatrix-glpk-0.19.0.0@sha256:cf46c54bc3878bd207674ad88c3389083809f4df862df68ee64c6708dc517a52,1683
- inline-c-cpp-0.4.0.3@sha256:afebd9a9e710da8097d647e1f05b7ba5a6b411e7fdc0ad02c4748b007f83af02,3605

allow-newer: false
resolver: lts-19.25
